### ISSUE TITLE
Last Character is Dropped from Last WhoisResponse.RespondedServers: whois.afrinic.ne and whois.krnic.ne

### ISSUE THREAD

**Issue by ajstadlin** [keithjjones/WhoisClient.NET#1]
For example:
`WhoisResponse` who = WhoisClient.Query(150.126.0.0);

The following are the who.RespondedServers[0..2] values
"whois.iana.net"
"whois.arin.net"
"**whois.afrinic.ne**"

Notice that the "t" is missing from "whois.afrinic.ne"

Similarly, 150.242.144.0 results in the "t" being dropped from "whois.krnic.net" leaving
`RespondedServers[2]` == "**whois.krnic.ne**"

**Comment by keithjjones** [comment]
Thanks @ajstadlin.  Confirmed and squashed in 04939d461c628c574976ef4a686bcde9c298e2c0.  I pushed a new package to NuGet.  It may take a few minutes to show up.  Reopen this issue if I did not completely kill the bug.

**Comment by ajstadlin** [comment]
THANKS - Works Great!

**Comment by keithjjones** [comment]
:+1: Thanks for bringing it up.  I would have never caught it without your help.
