### ISSUE TITLE
UTF8 Encoded Response

### ISSUE THREAD

**Issue by ajstadlin** [keithjjones/WhoisClient.NET#2]
I'm not sure if the response encoding is part of the WhoisClient.NET processing or not.  Maybe my application needs to change the WhoisClient's response's encoding?  It would be nice to be able to read the Whois data returned in non-ASCII encoded languages like Hangul.  

Attached is a screen shot showing that, although my text box can take Hangul input and display it (the highlighted text in the textbox tests this), the text from the WhoisClient's response shows "????" instead of Hangul.

I don't consider this a "bug", and I'm not sure yet if this could be happening in my own application code when it adds the response text to the TextBox.Text.  It will be nice to get this working.

![utf8-or-unicode-would_be_nice](https://cloud.githubusercontent.com/assets/14024430/15016999/d2b581b6-11e1-11e6-898e-16a2ada6cb01.png)

**Comment by keithjjones** [comment]
@ajstadlin I am not sure how to approach this request.  If you or perhaps @jsakamoto have any ideas on how to address this request I would be happy to incorporate them.

Have you looked through this code to see how this request could be addressed?  Probably the easiest thing to do is set up a new test for that particular language and trace backwards from there.

**Comment by ajstadlin** [comment]
Oops!  I should have looked more closely at the source code.  I simply have to pass the Encoding.UTF8 as a parameter in the WhoisClient.Query() procedure!  The WhoisClient.NET works excellently!

This issue is corrected in my application's code as follows (screen shot attached):

`WhoisResponse wiReply = WhoisClient.Query("14.4.0.0", null, 43, Encoding.UTF8);`

![utf8-or-unicode](https://cloud.githubusercontent.com/assets/14024430/15018191/9375350a-11e6-11e6-92dd-e71acabe0aae.png)

**Comment by keithjjones** [comment]
Awesome!  If your request is addressed fully, please close the issue.
